domain_path: /home/murphyj/Vivado/color_leds_with_interrupts/platform/export/platform/sw/standalone_ps7_cortexa9_0
app_src_dir: /opt/Xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_apps/empty_application
template: empty_application
